apiVersion: v1
kind: ConfigMap
metadata:
  name: edgemesh-agent-cfg
  namespace: kubeedge
  labels:
    k8s-app: kubeedge
    kubeedge: edgemesh-agent
data:
  edgemesh-agent.yaml: |
    # For more detailed configuration, please refer to: https://edgemesh.netlify.app/reference/config-items.html#edgemesh-agent-cfg
    commonConfig:
      bridgeDeviceName: edgemesh0
      bridgeDeviceIP: 169.254.96.16
    modules:
      edgeDNS:
        enable: true
        listenPort: 53
        cacheDNS:
          enable: true
          autoDetect: true
          upstreamServers:
          - 10.96.0.10
          - 1.1.1.1
          cacheTTL: 30
      edgeProxy:
        enable: true
      edgeTunnel:
        enable: true
        listenPort: 20006
        relayNodes:
        - nodeName: kubeedge1 
          advertiseAddress:
          - 13.91.228.133
          - 10.0.2.17
        - nodeName: kubeedge2
          advertiseAddress:
          - 10.0.2.18
        - nodeName: kubeedge3
          advertiseAddress:
          - 10.0.2.19
        - nodeName: edge7
          advertiseAddress:
          - 10.0.2.11
        - nodeName: edge8
          advertiseAddress:
          - 10.0.2.12
        tunnelLimitConfig:
          enable: true
          tunnelBaseStreamIn: 10240
          tunnelBaseStreamOut: 10240
          TunnelPeerBaseStreamIn: 1024
          tunnelPeerBaseStreamOut: 1024
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: edgemesh-agent-psk
  namespace: kubeedge
  labels:
    k8s-app: kubeedge
    kubeedge: edgemesh-agent
data:
  # Generated by `openssl rand -base64 32`
  # NOTE: Don't use this psk, please regenerate it!!! Please refer to: https://edgemesh.netlify.app/guide/security.html
  psk: JugH9HP1XBouyO5pWGeZa8LtipDURrf17EJvUHcJGuQ=
