apiVersion: v1
kind: ConfigMap
metadata:
  name: edgemesh-gateway-cfg
  namespace: kubeedge
  labels:
    k8s-app: kubeedge
    kubeedge: edgemesh-gateway
data:
  edgemesh-gateway.yaml: |
    # For more detailed configuration, please refer to: https://edgemesh.netlify.app/reference/config-items.html#edgemesh-gateway-cfg
    modules:
      kubeAPIConfig:
        master: https://13.91.228.133:8443
        contentType: application/vnd.kubernetes.protobuf
        qps: 100
        burst: 200
        kubeConfig: /root/.kube/config
        metaServer:
          server: http://127.0.0.1:10550
          security:
            requireAuthorization: false
            insecureSkipTLSVerify: true
        deleteKubeConfig: false
      edgeGateway:
        enable: true
      edgeTunnel:
        enable: true
        listenPort: 20006
        relayNodes:
        - nodeName: kubeedge1
          advertiseAddress:
          - 13.91.228.133
          - 10.0.2.17
        - nodeName: kubeedge2
          advertiseAddress:
          - 10.0.2.18
        - nodeName: kubeedge3
          advertiseAddress:
          - 10.0.2.19
        tunnelLimitConfig:
          enable: false
          tunnelBaseStreamIn: 10240
          tunnelBaseStreamOut: 10240
          TunnelPeerBaseStreamIn: 1024
          tunnelPeerBaseStreamOut: 1024
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: edgemesh-gateway-psk
  namespace: kubeedge
  labels:
    k8s-app: kubeedge
    kubeedge: edgemesh-gateway
data:
  # Generated by `openssl rand -base64 32`
  # NOTE: Don't use this psk, please regenerate it!!! Please refer to: https://edgemesh.netlify.app/guide/security.html
  psk: JugH9HP1XBouyO5pWGeZa8LtipDURrf17EJvUHcJGuQ=
